### ISSUE TITLE
Question How to register with submitGit

### ISSUE THREAD

**Issue by dhanvi** [rtyley/submitgit#1]
`As well as being verified in GitHub, your email must be registered with submitGit, to allow submitGit to send emails with your address as the 'From:' field.`

`Register your email address with submitGit's Amazon SES account in order for it to send emails from you.`

Well how can I do it. (Well I think it's not yet implemented)

Also you need to make sure that the patch was based on the `next` branch not the master.

Well this is a cool project but doing the hard way is the best way IMO

**Comment by rtyley** [comment]
> Well how can I do it. (Well I think it's not yet implemented)

Hi @dhanvi - if you send a preview email to yourself from submitGit, there will be a link at the bottom of the email:

```
This is a preview - if you want to send this message for real, click here:
https://submitgit.herokuapp.com/git/git/pull/1/xxxxx/yyyy
```

If you click it, a SES verification message will be sent to you for registration, and you'll see a message like this on the page:

```
Great! Now, please check your email for an "Amazon SES Address Verification Request"

Click the link in that email to grant submitGit permission to send emails to the Git mailing list with your address in the 'From:' field
```


> Also you need to make sure that the patch was based on the next branch not the master.

Hmm, the user selects the branch when they create the PR, so the best I can do is guide them to consider the branch they're on:

https://github.com/rtyley/submitgit/blob/ffc6078b/app/views/fragments/patchBaseGuidelines.scala.html

This what I based that on:

https://github.com/git/git/blob/6c1249c5/Documentation/SubmittingPatches#L4-L31

...from that guidance, I'm not sure why you say the branch should be `next`? Is there some other reference I should be looking at?



> Well this is a cool project but doing the hard way is the best way IMO

Thank you! and if this way is better for even _some_ people, I'm happy :smile:

**Comment by dhanvi** [comment]
@rtyley got the email working :+1: 

Well you can't do anything with the branch other than suggesting the person to read the documentation (It was my mistake it should have been based on the `maint` in general)

This will be helpful to the newbies like me who are thinking of contributing to git :smile: Hope we can see more people using this in the future 

Feature suggestion :- 
You can also create a way to send the set of patches (I am not sure how you could implement it based on pull requests )
