### ISSUE TITLE
Invalid CSRF token found in form body

### ISSUE THREAD

**Issue by dscho** [rtyley/submitgit#22]
I just wanted to send a preview for https://submitgit.herokuapp.com/git/git/pull/173 and instead I was greeted with this error:

```
Invalid CSRF token found in form body
```

When I refreshed, it did the same.

However, a quick web search ended up [here](https://www.reddit.com/r/programming/comments/3ephdf/weekend_project_onlinebased_collection_of_useful/) and suggested to open the page in a fresh tab. And there it worked!

The difference was of course the GitHub authentication, I had not directed my browser to submitGit for a few days... Maybe there is a way around the error in that case?

**Comment by rtyley** [comment]
Not entirely sure what's going on, will look when I get a chance.

The error is raised here: https://github.com/playframework/playframework/blob/2.4.2/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala#L131

To be clear, you were clicking the 'Send' button when this happened?

**Comment by dscho** [comment]
Yep, "Send" to send a preview mail.
