### ISSUE TITLE
.gitignore file does not work when saved as UTF-8 + BOM

### ISSUE THREAD

**Issue by Download** [rtyley/submitgit#24]
Removing the BOM makes it work.
This is very unfortunate as it prevents us from writing out the BOM for `.gitignore` files, effectively making applications *guess* the encoding i.s.o. being able to *detect* it.
The Unicode spec mandates conforming applications to accept the BOM.
If Git does not support Unicode this issue can be closed (but that would be another issue :)

**Comment by rtyley** [comment]
This sounds like a bug with git, rather than submitGit?

**Comment by Download** [comment]
Ah sorry! Wrong issue tracker I guess
