### ISSUE TITLE
enable service for other projects != git

### ISSUE THREAD

**Issue by henning-schild** [rtyley/submitgit#41]
Really nice idea to send the mails on behalf of users. Many projects share the problem that contributers want something as easy as a PR to get started. What would it take to apply that to other projects as well?

I guess a patch against `app/lib/ProjectRepo.scala`, but you probably would not want to send the mails for many projects.

So i guess it would take a clone and patches to change the project, and running the bot somewhere ... AWS? And getting the API connection to connect the app. Maybe you can elaborate on that.

**Comment by rtyley** [comment]
> Really nice idea to send the mails on behalf of users. Many projects share the problem that contributers want something as easy as a PR to get started. 

I can believe that - the majority of new contributors these days are going to be more familiar with a GitHub-like contribution process, and have probably never submitted diff-formatted matches to mailing lists before. Creating _submitgit_ was a bit of an act of desperation on my part - the git project wasn't able to reach a consensus to accept anything but mailing list submissions.

Are there any particular projects you have in mind? Are they definitely committed to mailing-list only submissions...?!

> What would it take to apply that to other projects as well?

Yep, a patch to ProjectRepo.scala would open up new repos, though as you say I might not want - and you might not want - me to be the one running the server. I might need to think about that. Running an instance of submitgit needs a reasonable host (heroku is easiest) but also a registered Amazon SES account. The volume of emails has so far been relatively manageable. I also wouldn't want to start sending automated emails to a mailing list without first getting a consensus from the mailing list that they welcome them!

**Comment by henning-schild** [comment]
Thanks. The projects i have in mind are committed to mailing-list only. Let me get in touch with the maintainers and see if they would be interested. If so i might get back to you, if it gets adopted we might need some restructuring to keep sharing your base between projects.
